### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by dscalzi** [dscalzi/Nebula#2]
This is a *non-comprehensive* list of things that still need to be done. Items will be added as they come up.

#### Forge
* [x] Forge 1.7-1.12 adapter.
* [x] Forge Mod 1.7-1.12 processing.
* [x] Forge 1.13+ adapter.
* [x] Forge Mod 1.13+ processing.
* [ ] Reference forgemods which are hosted on curseforge (mods that do not allow distribution from external hosts).
* [ ] Forge complete.

#### Liteloader
* [ ] Liteloader 1.7-1.12 adapter.
  * [ ] Artifact processing based off http://dl.liteloader.com/versions/versions.json
* [ ] Litemod 1.7-1.12 processing.
* [ ] Update Liteloader handling on Helios Launcher
  * [ ] Litemods should no longer be submodules of liteloader.
  * [ ] Litemods should not even be processed if no liteloader is provided.
  * [ ] Liteloader required libraries should be liteloader submodules to support a forge-less server configuration.
  * [ ] All tested and verified.
* [ ] Liteloader complete

#### Files
* [ ] Resolve files beyond a single depth.
* [ ] Files complete.

#### General
* [ ] Submodule processing (invoke main processor on subfile and append resolved modules).
* [ ] Metadata preservation (possibly add to servermeta.json).
* [ ] Distribution merges (not sure if needed).
* [ ] Distribution validations (not sure if still needed).
* [ ] General complete.

**Comment by SirOMGitsYOU** [comment]
Would you consider adding native Fabric Support?

**Comment by Psycho649** [comment]
I would like to know when Helios Launcher v2 will be complete @dscalzi 
I need vanilla support badly

**Comment by gamernitro999** [comment]
> I would like to know when Helios Launcher v2 will be complete @dscalzi I need vanilla support badly

will arrive when ready (you can have vanilla just do it yourself)

**Comment by dscalzi** [comment]
It's not being worked on, don't wait for it.
